In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("01_data/raw/dataset_raw.csv")

df.head()

,OrderID,Date,Customer,Region,Product,Category,Quantity,UnitPrice,Sales
0,1001,2025-11-26,Customer_28,North,Chair,Furniture,6,90,540
1,1002,2025-09-05,Customer_54,West,Desk,Furniture,5,150,750
2,1003,2025-02-23,Customer_89,South,Printer,Electronics,4,200,800
3,1004,2025-11-25,Customer_36,South,Printer,Electronics,2,200,400
4,1005,2025-05-09,Customer_118,North,Notebook,Stationery,6,5,30

In [3]:
df.shape

(500, 9)

In [4]:
duplicates = df.duplicated().sum()

print("Duplicate Rows:", duplicates)

Duplicate Rows: 0

In [5]:
df = df.drop_duplicates()

In [6]:
df["Date"] = pd.to_datetime(df["Date"])

In [7]:
df["Order Year"] = df["Date"].dt.year

df["Order Month"] = df["Date"].dt.month_name()

In [8]:
categorical = df.select_dtypes(include=["object", "string"]).columns

for col in categorical:
    df[col] = df[col].fillna("Unknown")

In [9]:
numeric = df.select_dtypes(include="number").columns

for col in numeric:
    df[col] = df[col].fillna(df[col].median())

In [10]:
print(df.columns.tolist())

['OrderID', 'Date', 'Customer', 'Region', 'Product', 'Category', 'Quantity', 'UnitPrice', 'Sales', 'Order Year', 'Order Month']

In [11]:
import numpy as np

df["High Value Order"] = np.where(
    df["Sales"] >= 1000,
    "Yes",
    "No"
)

In [12]:
df["Sales Category"] = pd.cut(
    df["Sales"],
    bins=[0, 500, 1000, float("inf")],
    labels=["Low", "Medium", "High"]
)

In [13]:
df["Total Price"] = df["Quantity"] * df["UnitPrice"]

In [14]:
df.to_csv(
    "01_data/processed/dataforge_cleaned.csv",
    index=False
)

print("Dataset exported successfully!")

Dataset exported successfully!

In [15]:
df.head()

,OrderID,Date,Customer,Region,Product,Category,Quantity,UnitPrice,Sales,Order Year,Order Month,High Value Order,Sales Category,Total Price
0,1001,2025-11-26,Customer_28,North,Chair,Furniture,6,90,540,2025,November,No,Medium,540
1,1002,2025-09-05,Customer_54,West,Desk,Furniture,5,150,750,2025,September,No,Medium,750
2,1003,2025-02-23,Customer_89,South,Printer,Electronics,4,200,800,2025,February,No,Medium,800
3,1004,2025-11-25,Customer_36,South,Printer,Electronics,2,200,400,2025,November,No,Low,400
4,1005,2025-05-09,Customer_118,North,Notebook,Stationery,6,5,30,2025,May,No,Low,30