In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("01_data/processed/dataforge_cleaned.csv")

In [3]:
df.head()

,OrderID,Date,Customer,Region,Product,Category,Quantity,UnitPrice,Sales,Order Year,Order Month,High Value Order,Sales Category,Total Price
0,1001,2025-11-26,Customer_28,North,Chair,Furniture,6,90,540,2025,November,No,Medium,540
1,1002,2025-09-05,Customer_54,West,Desk,Furniture,5,150,750,2025,September,No,Medium,750
2,1003,2025-02-23,Customer_89,South,Printer,Electronics,4,200,800,2025,February,No,Medium,800
3,1004,2025-11-25,Customer_36,South,Printer,Electronics,2,200,400,2025,November,No,Low,400
4,1005,2025-05-09,Customer_118,North,Notebook,Stationery,6,5,30,2025,May,No,Low,30

In [4]:
numeric_summary = df.describe().T

numeric_summary

,count,mean,std,min,25%,50%,75%,max
OrderID,500.0,1250.500,144.481833,1001.0,1125.75,1250.5,1375.25,1500.0
Quantity,500.0,5.458,2.917750,1.0,3.00,6.0,8.00,10.0
UnitPrice,500.0,220.610,283.366850,5.0,20.00,90.0,200.00,800.0
Sales,500.0,1174.090,1794.477423,5.0,100.00,495.0,1200.00,8000.0
Order Year,500.0,2025.000,0.000000,2025.0,2025.00,2025.0,2025.00,2025.0
Total Price,500.0,1174.090,1794.477423,5.0,100.00,495.0,1200.00,8000.0

In [5]:
numeric_summary.to_csv(
    "04_python/outputs/tables/numeric_summary.csv"
)

In [6]:
missing = pd.DataFrame({
    "Missing Count": df.isna().sum(),
    "Missing Percent": (df.isna().mean()*100).round(2)
})

missing.sort_values(
    by="Missing Percent",
    ascending=False,
    inplace=True
)

missing

                  Missing Count  Missing Percent
OrderID                       0              0.0
Date                          0              0.0
Customer                      0              0.0
Region                        0              0.0
Product                       0              0.0
Category                      0              0.0
Quantity                      0              0.0
UnitPrice                     0              0.0
Sales                         0              0.0
Order Year                    0              0.0
Order Month                   0              0.0
High Value Order              0              0.0
Sales Category                0              0.0
Total Price                   0              0.0

In [7]:
missing.to_csv(
    "04_python/outputs/tables/missing_percent.csv"
)

In [8]:
category_sales = (
    df.groupby("Category")["Sales"]
      .sum()
      .reset_index()
      .sort_values("Sales", ascending=False)
)

category_sales

      Category   Sales
0  Electronics  479600
1    Furniture  105540
2   Stationery    1905

In [9]:
category_sales.to_csv(
    "04_python/outputs/tables/category_sales.csv",
    index=False
)

In [10]:
region_sales = (
    df.groupby("Region")["Sales"]
      .sum()
      .reset_index()
      .sort_values("Sales", ascending=False)
)

region_sales

  Region   Sales
1  North  161655
3   West  147275
0   East  144845
2  South  133270

In [11]:
region_sales.to_csv(
    "04_python/outputs/tables/region_sales.csv",
    index=False
)

In [12]:
year_sales = (
    df.groupby("Order Year")["Sales"]
      .sum()
      .reset_index()
)

year_sales

   Order Year   Sales
0        2025  587045

In [13]:
year_sales.to_csv(
    "04_python/outputs/tables/year_sales.csv",
    index=False
)

In [14]:
category_quantity = (
    df.groupby("Category")["Quantity"]
      .sum()
      .reset_index()
      .sort_values("Quantity", ascending=False)
)

category_quantity

      Category  Quantity
0  Electronics      1468
1    Furniture       880
2   Stationery       381

In [15]:
category_quantity.to_csv(
    "04_python/outputs/tables/category_quantity.csv",
    index=False
)

In [16]:
top10 = (
    df.nlargest(10, "Sales")
)

top10

,OrderID,Date,Customer,Region,Product,Category,Quantity,UnitPrice,Sales,Order Year,Order Month,High Value Order,Sales Category,Total Price
89,1090,2025-04-26,Customer_13,East,Laptop,Electronics,10,800,8000,2025,April,Yes,High,8000
129,1130,2025-01-30,Customer_142,West,Laptop,Electronics,10,800,8000,2025,January,Yes,High,8000
171,1172,2025-02-14,Customer_113,South,Laptop,Electronics,10,800,8000,2025,February,Yes,High,8000
244,1245,2025-12-06,Customer_49,North,Laptop,Electronics,10,800,8000,2025,December,Yes,High,8000
281,1282,2025-01-25,Customer_45,North,Laptop,Electronics,10,800,8000,2025,January,Yes,High,8000
311,1312,2025-06-17,Customer_139,South,Laptop,Electronics,10,800,8000,2025,June,Yes,High,8000
412,1413,2025-04-22,Customer_2,North,Laptop,Electronics,10,800,8000,2025,April,Yes,High,8000
499,1500,2025-05-28,Customer_19,North,Laptop,Electronics,10,800,8000,2025,May,Yes,High,8000
20,1021,2025-05-29,Customer_67,North,Laptop,Electronics,9,800,7200,2025,May,Yes,High,7200
77,1078,2025-12-28,Customer_53,East,Laptop,Electronics,9,800,7200,2025,December,Yes,High,7200

In [17]:
top10.to_csv(
    "04_python/outputs/tables/top10_sales.csv",
    index=False
)

In [18]:
bottom10 = (
    df.nsmallest(10, "Sales")
)

bottom10

,OrderID,Date,Customer,Region,Product,Category,Quantity,UnitPrice,Sales,Order Year,Order Month,High Value Order,Sales Category,Total Price
59,1060,2025-12-21,Customer_60,East,Notebook,Stationery,1,5,5,2025,December,No,Low,5
173,1174,2025-09-08,Customer_91,North,Notebook,Stationery,1,5,5,2025,September,No,Low,5
290,1291,2025-12-17,Customer_120,North,Notebook,Stationery,1,5,5,2025,December,No,Low,5
364,1365,2025-10-26,Customer_136,South,Notebook,Stationery,1,5,5,2025,October,No,Low,5
399,1400,2025-06-18,Customer_104,North,Notebook,Stationery,1,5,5,2025,June,No,Low,5
26,1027,2025-06-12,Customer_111,West,Notebook,Stationery,2,5,10,2025,June,No,Low,10
32,1033,2025-11-12,Customer_44,East,Notebook,Stationery,2,5,10,2025,November,No,Low,10
37,1038,2025-06-03,Customer_123,West,Notebook,Stationery,2,5,10,2025,June,No,Low,10
60,1061,2025-05-11,Customer_93,South,Notebook,Stationery,2,5,10,2025,May,No,Low,10
91,1092,2025-08-29,Customer_15,South,Notebook,Stationery,2,5,10,2025,August,No,Low,10

In [19]:
bottom10.to_csv(
    "04_python/outputs/tables/bottom10_sales.csv",
    index=False
)